FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/train.py .
COPY src/generate_mock_data.py .

RUN mkdir data models

CMD ["sh", "-c", "python generate_mock_data.py && python train.py"]